---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-nextjs
  name: frontend-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nextjs
  template:
    metadata:
      annotations:
        deployment.omnishore.ma/commit: "$CI_COMMIT_SHA"
        deployment.omnishore.ma/id: "$CI_JOB_ID"
        kubectl.kubernetes.io/restartedAt: ""
      labels:
        app: frontend-nextjs
    spec:
      containers:
      - env:
        - name: BASE_URL_CMS
          value: http://backend.7adith.ma:8000
        - name: BASE_URL_ES
          value: http://elasticsearch:9200
        image: registry.devops.os/minassat-mohammed-vi-du-hadith/frontend-nextjs:staging
        imagePullPolicy: Always
        name: frontend-nextjs
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred