stages:
  - containerize
  - deploy
  
build_image:
  stage: containerize
  image: docker:latest
  only:
    - master
  tags:
    - r0
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:staging -f .docker/Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:staging
    
deploy_image:
  stage: deploy
  image: 
    name: registry.devops.os/ci-tools/kubectl:1.22
    entrypoint: [""]
  tags:
    - r0
  only:
    - master
  script:
     - |
      envsubst < .k8s/frontend-nextjs-deploy.yml | kubectl apply -f -
