[[redirects]]
  from = "/*"
  to = "/pages/app.js"
  status = 200
[build]
  command = "npm install --save custom-event-polyfill@1.0.7 && npm i react-touch-screen-keyboard --legacy-peer-deps && npm run build"
